spring:
  datasource:
    url: jdbc:mysql://localhost:3306/genproj
    username: root
    password:
  jpa:
    database: HSQL
    hibernate:
      ddl-auto: create-drop
hibernate:
  hbm2ddl:
    auto: create