spring:
  datasource:
    url: jdbc:mysql://localhost:3306/genproj
    username: root
    password:
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: /
hibernate:
  hbm2ddl:
    auto: create